"""empty message

Revision ID: 989cf6ce39dd
Revises: c1028607a8e4
Create Date: 2017-09-14 11:38:26.935337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989cf6ce39dd'
down_revision = 'c1028607a8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'gid',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'gid',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
