"""empty message

Revision ID: c1028607a8e4
Revises: d219892d4e42
Create Date: 2017-09-14 10:21:40.087204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1028607a8e4'
down_revision = 'd219892d4e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('gid', sa.String(length=64), nullable=False))
    op.drop_column('group', 'name')
    op.drop_column('group', 'app_id')
    op.drop_column('group', 'access_token')
    op.drop_column('group', 'secure_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('secure_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('app_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('group', 'gid')
    # ### end Alembic commands ###
