"""empty message

Revision ID: cba1a13e95f1
Revises: 989cf6ce39dd
Create Date: 2017-09-14 17:13:23.717867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba1a13e95f1'
down_revision = '989cf6ce39dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'source')
    # ### end Alembic commands ###
