"""empty message

Revision ID: da9fab729ba5
Revises: cba1a13e95f1
Create Date: 2018-05-30 18:36:43.941314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9fab729ba5'
down_revision = 'cba1a13e95f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('common_users', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'common_users')
    # ### end Alembic commands ###
